### ISSUE TITLE
Cannot invoke "org.springframework.security.core.Authentication.getName()" because "authentication" is null

### ISSUE THREAD

**Issue by parunev** [callicoder/spring-boot-react-oauth2-social-login-demo#80]
While trying to save the User I'm getting this error, I've tried anything from changing my code to be completely like yours...

```org.springframework.security.authentication.InternalAuthenticationServiceException: Cannot invoke "org.springframework.security.core.Authentication.getName()" because "authentication" is null
	at com.docconnect.docconnect.config.oauth2.service.CustomOAuth2UserService.loadUser(CustomOAuth2UserService.java:39) ~[classes/:na]
	at org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationProvider.authenticate(OAuth2LoginAuthenticationProvider.java:117) ~[spring-security-oauth2-client-6.1.2.jar:6.1.2]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-6.1.2.jar:6.1.2]
	at org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter.attemptAuthentication(OAuth2LoginAuthenticationFilter.java:195) ~[spring-security-oauth2-client-6.1.2.jar:6.1.2]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar:6.1.2]```

**Comment by parunev** [comment]
I want to mention that I'm currently implementing it in the REST API because I don't have access to the front-end, so yeah I want to redirect to URL api/hello-world for now if that might be a problem too

**Comment by volkaris** [comment]
how did you fix this?
